### PR TITLE
fix(test): update vllm_generate_endpoint to post-#68 launch_server_process API

### PR DESCRIPTION
**Pull request by aoshen02**
## Problem

`tests/test_vllm_generate_endpoint.py` raised at runtime:

```
TypeError: launch_server_process() got an unexpected keyword argument 'bind_host'
```

The test still called the **pre-#68** multi-kwarg form
`launch_server_process(bind_host=, server_port=, args=, rank=, visible_devices=, model_path=)`.
PR #68 (multi-node rollout topology) refactored `launch_server_process` to take a
single `server_args` dict produced by `_compute_server_args(...)` — see
`VLLMEngine` itself at `vime/backends/vllm_utils/vllm_engine.py` (`_compute_server_args(...)` → `launch_server_process(self._server_args)`).

So this test has been failing since #68 and went unnoticed: the "Unit & utils"
job is gated behind `pre-commit`, which currently fails on every PR, so the job
is skipped. (Surfaced while running the full CI matrix for #121 on gb200; the
failure is **not** caused by #121 — the `bind_host` line predates it, from #16.)

## Fix

Test-only change — mirror how `VLLMEngine` launches the server:

- build `server_args` via `_compute_server_args(args, rank=0, dist_init_addr=None, host="127.0.0.1", port=server_port, base_gpu_id=0)`, then `launch_server_process(server_args)`.
- `base_gpu_id=0` pins this single-engine rank-0 server to the first visible GPU, sidestepping the rollout-placement math in `get_base_gpu_id` (which needs a full actor/critic placement Namespace).
- expand the `args` Namespace with the attrs `_compute_server_args` / `build_vllm_cmd_and_env` read (`num_gpus_per_node`, `hf_checkpoint`, `vllm_enable_sleep_mode`, `vllm_dp_size`).
- drop the now-unused `_visible_devices` helper.

**No production code change** (deliberately not re-adding `bind_host` to `launch_server_process`, which would regress the #68 dict API).

## Verification

`test_qwen3_0_6b_vllm_inference_generate_endpoint` now passes on a single GPU:

```
1 passed, 2 warnings in 89.49s
```

(Qwen3-0.6B, real `vllm serve` subprocess + `/inference/v1/generate` rollout path, arm64 sync1916 image.)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by CalvinXKY — APPROVED** [review]
LGTM
